/**
 * Mirrors frontend/src/data/resources.js exactly, `id` renamed to `_id` for
 * Mongo. If you add a resource here, add the matching one there too — until the
 * frontend is wired to GET /api/resources, both lists have to agree by hand.
 */
module.exports = [
  // ---- Rooms ----
  {
    _id: 'LT-1',
    kind: 'Room',
    category: 'Lecture theatre',
    name: 'Main Lecture Theatre',
    location: 'Faculty of Computing · Level 1',
    capacity: 180,
    features: ['Projector', 'Microphone', 'Air conditioning'],
  },
  {
    _id: 'LT-3',
    kind: 'Room',
    category: 'Lecture theatre',
    name: 'Lecture Theatre 3',
    location: 'Faculty of Computing · Level 2',
    capacity: 120,
    features: ['Projector', 'Air conditioning'],
  },
  {
    _id: 'LAB-A',
    kind: 'Room',
    category: 'Lab',
    name: 'Software Lab A',
    location: 'Faculty of Computing · Level 3',
    capacity: 40,
    features: ['40 workstations', 'Projector', 'Air conditioning'],
  },
  {
    _id: 'LAB-B',
    kind: 'Room',
    category: 'Lab',
    name: 'Networking Lab',
    location: 'Faculty of Computing · Level 3',
    capacity: 30,
    features: ['Cisco rack', 'Projector'],
  },
  {
    _id: 'LAB-C',
    kind: 'Room',
    category: 'Lab',
    name: 'Multimedia Lab',
    location: 'Faculty of Computing · Level 4',
    capacity: 24,
    features: ['iMac workstations', 'Colour-calibrated displays'],
  },
  {
    _id: 'SR-12',
    kind: 'Room',
    category: 'Study room',
    name: 'Study Room 12',
    location: 'Library · Level 2',
    capacity: 6,
    features: ['Whiteboard', 'Power outlets'],
  },
  {
    _id: 'SR-14',
    kind: 'Room',
    category: 'Study room',
    name: 'Study Room 14',
    location: 'Library · Level 2',
    capacity: 8,
    features: ['Whiteboard', 'Display', 'Power outlets'],
  },
  {
    _id: 'MR-2',
    kind: 'Room',
    category: 'Meeting room',
    name: 'Project Meeting Room 2',
    location: 'Faculty of Computing · Level 1',
    capacity: 12,
    features: ['Display', 'Conference phone', 'Whiteboard'],
  },

  // ---- Equipment ----
  {
    _id: 'PRJ-014',
    kind: 'Equipment',
    category: 'Projector',
    name: 'Portable Projector',
    location: 'AV Store · Level 1',
    capacity: 1,
    features: ['1080p', 'HDMI + USB-C', 'Carry case'],
  },
  {
    _id: 'CAM-03',
    kind: 'Equipment',
    category: 'Camera kit',
    name: 'DSLR Camera Kit',
    location: 'AV Store · Level 1',
    capacity: 1,
    features: ['DSLR body', 'Tripod', 'Shotgun mic'],
  },
  {
    _id: 'SND-05',
    kind: 'Equipment',
    category: 'Audio',
    name: 'Portable PA Kit',
    location: 'AV Store · Level 1',
    capacity: 1,
    features: ['2 speakers', '2 wireless mics', 'Mixer'],
  },
  {
    _id: 'LAP-27',
    kind: 'Equipment',
    category: 'Laptop',
    name: 'Loan Laptop',
    location: 'IT Helpdesk · Level 1',
    capacity: 1,
    features: ['16 GB RAM', 'Docker preinstalled'],
  },
  {
    _id: 'VR-01',
    kind: 'Equipment',
    category: 'XR',
    name: 'VR Headset Kit',
    location: 'Multimedia Lab store',
    capacity: 1,
    features: ['Headset', '2 controllers', 'Base stations'],
  },
  {
    _id: 'IOT-09',
    kind: 'Equipment',
    category: 'Lab kit',
    name: 'IoT Prototyping Kit',
    location: 'Electronics Lab store',
    capacity: 1,
    features: ['Arduino + ESP32', 'Sensor pack', 'Breadboards'],
  },
]
